using System.Globalization;
using System.Numerics;
using System.Text;
using OcctSharp.Generator.Model;
using OcctSharp.Generator.Transformation;
using OcctSharp.Generator.TypeMapping;

namespace OcctSharp.Generator.Emission;

public static class EnumBindingEmitter
{
    public static GeneratedBindingSet Emit(
        string occtVersion,
        BindingModel model,
        IReadOnlyCollection<string> selectedStableIds)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(occtVersion);
        ArgumentNullException.ThrowIfNull(model);
        ArgumentNullException.ThrowIfNull(selectedStableIds);

        if (selectedStableIds.Count == 0)
        {
            return new GeneratedBindingSet(occtVersion, [], []);
        }

        HashSet<string> selected = selectedStableIds.ToHashSet(StringComparer.Ordinal);
        InitialTypeMap typeMap = InitialTypeMap.FromModel(model);
        Dictionary<string, BindingDeclaration> enumByManagedName = model.Declarations
            .Where(static declaration => declaration.Kind == BindingDeclarationKind.Enum)
            .GroupBy(static declaration => ToManagedTypeName(declaration.NativeName), StringComparer.Ordinal)
            .ToDictionary(
                static group => group.Key,
                static group => group.OrderByDescending(static declaration => declaration.EnumValues.Count)
                    .ThenBy(static declaration => declaration.StableId, StringComparer.Ordinal)
                    .First(),
                StringComparer.Ordinal);

        HashSet<string> referencedEnumNames = [];
        foreach (BindingDeclaration declaration in model.Declarations.Where(item => selected.Contains(item.StableId)))
        {
            if (declaration.Kind == BindingDeclarationKind.Enum)
            {
                referencedEnumNames.Add(ToManagedTypeName(declaration.NativeName));
            }
            if (declaration.ReturnType is not null)
            {
                AddEnumType(declaration.ReturnType, BindingTypeUsage.ReturnValue, typeMap, referencedEnumNames);
            }
            foreach (BindingParameter parameter in declaration.Parameters)
            {
                AddEnumType(parameter.Type, BindingTypeUsage.Parameter, typeMap, referencedEnumNames);
            }
        }

        BindingDeclaration[] enums = referencedEnumNames
            .Order(StringComparer.Ordinal)
            .Select(name => enumByManagedName.TryGetValue(name, out BindingDeclaration? declaration)
                ? declaration
                : throw new InvalidDataException($"Referenced managed enum '{name}' has no discovered declaration."))
            .ToArray();
        if (enums.Length == 0)
        {
            return new GeneratedBindingSet(occtVersion, [], []);
        }

        ValidateManagedNames(enums);
        GeneratedFile[] files = enums
            .GroupBy(GetProductModule)
            .OrderBy(static group => group.Key)
            .Select(group => new GeneratedFile(
                $"src/OcctSharp/Generated/{group.Key}/{group.Key}.Enums.Generated.cs",
                EmitModule(group.OrderBy(static declaration => declaration.StableId, StringComparer.Ordinal).ToArray()),
                group.Key,
                GeneratedApiLayer.SafeManaged,
                "Enums.ManagedFriendly"))
            .ToArray();

        return new GeneratedBindingSet(
            occtVersion,
            enums.Select(static declaration => declaration.StableId).Order(StringComparer.Ordinal).ToArray(),
            files);
    }

    private static string EmitModule(IReadOnlyList<BindingDeclaration> enums)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated />");
        foreach (BindingDeclaration declaration in enums)
        {
            builder.AppendLine("// Source: " + declaration.StableId);
        }
        builder.AppendLine();
        builder.AppendLine("namespace OcctSharp;");

        foreach (BindingDeclaration declaration in enums)
        {
            if (declaration.EnumValues.Count == 0)
            {
                throw new InvalidDataException($"Enum '{declaration.NativeName}' has no discovered values.");
            }

            builder.AppendLine();
            builder.AppendLine(CultureInfo.InvariantCulture, $"/// <summary>Generated value projection for OCCT {declaration.NativeName}.</summary>");
            builder.AppendLine(CultureInfo.InvariantCulture, $"public enum {ToManagedTypeName(declaration.NativeName)}");
            builder.AppendLine("{");
            for (int index = 0; index < declaration.EnumValues.Count; index++)
            {
                BindingEnumValue value = declaration.EnumValues[index];
                BigInteger numericValue = BigInteger.Parse(value.Value, CultureInfo.InvariantCulture);
                if (numericValue < int.MinValue || numericValue > int.MaxValue)
                {
                    throw new InvalidDataException(
                        $"Enum value '{declaration.NativeName}::{value.Name}' is outside the verified 32-bit ABI range.");
                }
                builder.AppendLine(CultureInfo.InvariantCulture, $"    /// <summary>OCCT value {value.Name}.</summary>");
                builder.AppendLine(CultureInfo.InvariantCulture, $"    {ToIdentifier(value.Name)} = {numericValue}{(index + 1 == declaration.EnumValues.Count ? string.Empty : ",")}");
            }
            builder.AppendLine("}");
        }

        return Normalize(builder.ToString());
    }

    private static OcctProductModule GetProductModule(BindingDeclaration declaration) =>
        declaration.ProductModule != OcctProductModule.Unassigned
            ? declaration.ProductModule
            : OcctProductModuleClassifier.ClassifyOrThrow(
                declaration.SourcePackage,
                declaration.SourceToolkit);

    private static void AddEnumType(
        BindingType type,
        BindingTypeUsage usage,
        InitialTypeMap typeMap,
        HashSet<string> names)
    {
        if (typeMap.TryMap(type, usage, out BindingTypeProjection? projection)
            && projection?.RuleId == "TM004")
        {
            names.Add(projection.ManagedFriendlyType);
        }
    }

    private static void ValidateManagedNames(IEnumerable<BindingDeclaration> enums)
    {
        string? duplicate = enums.GroupBy(static declaration => ToManagedTypeName(declaration.NativeName), StringComparer.Ordinal)
            .FirstOrDefault(static group => group.Count() > 1)?.Key;
        if (duplicate is not null)
        {
            throw new InvalidDataException($"Generated managed enum name '{duplicate}' is ambiguous.");
        }
    }

    private static string ToManagedTypeName(string nativeType)
    {
        string[] parts = nativeType.Split(['_', ':'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        return string.Concat(parts.Select(static part => char.ToUpperInvariant(part[0]) + part[1..]));
    }

    private static string ToIdentifier(string value)
    {
        StringBuilder builder = new(value.Length + 1);
        foreach (char character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }
        if (builder.Length == 0 || char.IsDigit(builder[0])) builder.Insert(0, '_');
        string identifier = builder.ToString();
        return CSharpKeywords.Contains(identifier) ? "@" + identifier : identifier;
    }

    private static string Normalize(string value) => value.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd('\n') + "\n";

    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while"
    };
}
