using System.Globalization;
using System.Text;
using OcctSharp.Generator.Model;
using OcctSharp.Generator.TypeMapping;

namespace OcctSharp.Generator.Emission;

internal static class GeometryValueEmitter
{
    internal const string HeaderInclude = "../Foundation/OcctSharp.Foundation.GeometryValues.Generated.h";

    internal static IEnumerable<GeneratedFile> Emit()
    {
        yield return new GeneratedFile("src/OcctSharp.Native/generated/Foundation/OcctSharp.Foundation.GeometryValues.Generated.h",
            NativeHeader(), OcctProductModule.Foundation, GeneratedApiLayer.Raw, "GeometryValues.NativeHeader");
        yield return new GeneratedFile("src/OcctSharp/Generated/Foundation/Foundation.GeometryValues.Generated.cs",
            ManagedRecords(), OcctProductModule.Foundation, GeneratedApiLayer.SafeManaged, "GeometryValues.ManagedRecords");
    }

    private static string NativeHeader()
    {
        StringBuilder b = new("// <auto-generated />\n#pragma once\n#include <stddef.h>\n");
        Dictionary<string, int> widths = new(StringComparer.Ordinal) { ["double"] = 8 };
        foreach (GeometryValueProjection value in GeometryValueProjections.All)
        {
            b.AppendLine("typedef struct " + value.AbiType + " {");
            foreach (GeometryValueField field in value.Fields)
                b.AppendLine("  " + (field.Type == "double" ? "double" : "OcctSharp_Value_" + field.Type) + " " + field.Name + ";");
            b.AppendLine("} " + value.AbiType + ";");
            widths.Add(value.Name, value.Fields.Sum(field => widths[field.Type]));
        }
        b.AppendLine("#ifdef __cplusplus");
        b.AppendLine("#include <cmath>\n#include <Standard_DomainError.hxx>\n#include <gp_Pnt.hxx>");
        foreach (GeometryValueProjection value in GeometryValueProjections.All) b.AppendLine("#include <" + value.NativeType + ".hxx>");
        foreach (GeometryValueProjection value in GeometryValueProjections.All)
        {
            b.AppendLine(CultureInfo.InvariantCulture, $"static_assert(sizeof({value.AbiType}) == {widths[value.Name]});");
            int offset = 0;
            foreach (GeometryValueField field in value.Fields)
            {
                b.AppendLine(CultureInfo.InvariantCulture, $"static_assert(offsetof({value.AbiType}, {field.Name}) == {offset});");
                offset += widths[field.Type];
            }
        }
        b.AppendLine("namespace OcctSharp_GeometryValues {");
        b.AppendLine("inline double Check(double value) { if (!std::isfinite(value)) throw Standard_DomainError(\"Geometric value must be finite.\"); return value; }");
        foreach (GeometryValueProjection value in GeometryValueProjections.All)
        {
            b.AppendLine("inline " + value.NativeType + " ToNative(" + value.AbiType + " value) {");
            b.AppendLine(value.Construct);
            b.AppendLine("}");
            b.AppendLine("inline " + value.AbiType + " FromNative(const " + value.NativeType + "& value) {");
            b.AppendLine("  return {" + string.Join(", ", value.Fields.Select(field => field.Type == "double"
                ? "value." + field.Accessor : "FromNative(value." + field.Accessor + ")")) + "};");
            b.AppendLine("}");
        }
        b.AppendLine("}\n#endif");
        return b.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }

    private static string ManagedRecords()
    {
        StringBuilder b = new("// <auto-generated />\nusing System.Runtime.InteropServices;\nnamespace OcctSharp.Values;\n");
        foreach (GeometryValueProjection value in GeometryValueProjections.All)
        {
            b.AppendLine("/// <summary>Copied " + value.NativeType + " value. Native calls validate finite inputs and geometric domains; no native storage is borrowed.</summary>");
            b.AppendLine("[StructLayout(LayoutKind.Sequential)]");
            b.AppendLine("public readonly record struct " + value.Name + "(" + string.Join(", ", value.Fields.Select(field => field.Type + " " + field.Name)) + ");");
        }
        return b.ToString().Replace("\r\n", "\n", StringComparison.Ordinal);
    }
}
