<Project>
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)win-x64\occt\*.dll">
      <Link>occt\%(Filename)%(Extension)</Link>
      <TargetPath>occt\%(Filename)%(Extension)</TargetPath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <Visible>false</Visible>
    </Content>
  </ItemGroup>
</Project>
