<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <OcctSharpPackageVersion Condition="'$(OcctSharpPackageVersion)' == ''">8.0.1-preview.8</OcctSharpPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OcctSharp" Version="$(OcctSharpPackageVersion)" />
  </ItemGroup>
</Project>
